"""Gemini client for generating daily reports via Vertex AI."""

import logging
from datetime import datetime

import vertexai
from vertexai.generative_models import GenerativeModel, GenerationConfig

from pipeline.config import (
    GCP_PROJECT,
    GEMINI_MODEL,
    GEMINI_LOCATION,
    GEMINI_TEMPERATURE,
)
from pipeline.mapper import DailyMetrics, Session

logger = logging.getLogger(__name__)

_initialized = False


def _ensure_init() -> None:
    """Initialize Vertex AI SDK once per process."""
    global _initialized
    if not _initialized:
        vertexai.init(project=GCP_PROJECT, location=GEMINI_LOCATION)
        _initialized = True
        logger.info(
            "Vertex AI initialized (project=%s, location=%s)",
            GCP_PROJECT,
            GEMINI_LOCATION,
        )


def _build_system_prompt() -> str:
    """Build the system instruction for the Gemini model."""
    return """You are an AI operations analyst for the H-Voice call agent system (HMCA).
Your task is to generate a daily markdown log following the exact template structure provided.

Guidelines:
- Use the provided metrics data and session summaries to fill every section.
- Be concise but insightful in the Summary section.
- For delta/comparison values, use the previous day report if provided; otherwise write "N/A" for deltas.
- Status indicators: use "🟢" for good/improved, "🟡" for neutral/stable, "🔴" for poor/declined.
- In Success Analysis, highlight patterns in successful calls (BANT completion, transfer effectiveness).
- In Failure Analysis, identify common failure modes and root causes.
- In Anomalies & Alerts, list any unusual patterns. If none, write "No anomalies detected."
- In Orchestrator Notes, provide actionable recommendations for improving agent performance.
- Output ONLY the markdown content. Do not wrap in code fences.
- Use the exact frontmatter format shown in the template."""


def _format_session_summary(session: Session, index: int) -> str:
    """Format a single session into a compact summary string for the prompt."""
    event_types = [e.event_type for e in session.events]
    bant = session.metadata.get("bant", {})
    bant_status = (
        "complete"
        if session.metadata.get("bant_complete")
        else f"partial ({len([v for v in bant.values() if v])}/4)"
    )
    duration = session.metadata.get("duration_seconds", 0)
    transferred = session.metadata.get("transferred", False)
    disposition = session.metadata.get("disposition", "unknown")

    return (
        f"Session {index + 1} [{session.session_id[:8]}]: "
        f"duration={duration:.0f}s, "
        f"events=[{' → '.join(event_types)}], "
        f"BANT={bant_status}, "
        f"transferred={'yes' if transferred else 'no'}, "
        f"disposition={disposition}"
    )


def _build_user_prompt(
    metrics: DailyMetrics,
    sessions: list[Session],
    date: str,
    previous_report: str | None = None,
) -> str:
    """Build the user prompt containing all data for report generation."""
    parts: list[str] = []

    parts.append(f"Generate the H-Voice Daily Log for {date}.")
    parts.append("")

    # Template structure reminder.
    parts.append("## Template Structure")
    parts.append("""Use this exact markdown structure:
---
date: {date}
agent: h-voice-call
type: daily-log
generated_at: {timestamp}
---

# H-Voice Daily Log — {date}

## Summary
> {one-paragraph summary}

## Key Metrics
| Metric | Value | vs Prev Day | Status |
|--------|-------|-------------|--------|
| Total Calls | {value} | {delta} | {status} |
| Connection Rate | {value}% | {delta}pp | {status} |
| BANT Completion Rate | {value}% | {delta}pp | {status} |
| Avg Call Duration | {value}s | {delta}s | {status} |
| Dealer Transfer Rate | {value}% | {delta}pp | {status} |

## Session Breakdown
### Success Analysis
{analysis of successful sessions}

### Failure Analysis
{analysis of failed sessions}

## Anomalies & Alerts
{anomalies list or "No anomalies detected."}

## Orchestrator Notes
{actionable recommendations}

---
*Generated by HMCA Agent Monitoring System*""")
    parts.append("")

    # Metrics data.
    parts.append("## Today's Metrics Data")
    parts.append(f"- Date: {metrics.date}")
    parts.append(f"- Total Calls: {metrics.total_calls}")
    parts.append(f"- Connected Calls: {metrics.connected_calls}")
    parts.append(f"- Connection Rate: {metrics.connection_rate}%")
    parts.append(f"- BANT Completion Rate: {metrics.bant_completion_rate}%")
    parts.append(f"- Avg Duration: {metrics.avg_duration_seconds}s")
    parts.append(f"- Transfer Rate: {metrics.transfer_rate}%")
    parts.append(f"- Successful Sessions: {len(metrics.success_sessions)}")
    parts.append(f"- Failed Sessions: {len(metrics.failure_sessions)}")
    parts.append(f"- Anomalies: {len(metrics.anomalies)}")
    parts.append("")

    if metrics.anomalies:
        parts.append("## Detected Anomalies")
        for anomaly in metrics.anomalies:
            parts.append(f"- {anomaly}")
        parts.append("")

    # Session summaries — cap to avoid exceeding context.
    max_sessions_in_prompt = 50

    if metrics.success_sessions:
        parts.append(f"## Successful Sessions ({len(metrics.success_sessions)} total)")
        for i, s in enumerate(metrics.success_sessions[:max_sessions_in_prompt]):
            parts.append(_format_session_summary(s, i))
        if len(metrics.success_sessions) > max_sessions_in_prompt:
            parts.append(f"... and {len(metrics.success_sessions) - max_sessions_in_prompt} more")
        parts.append("")

    if metrics.failure_sessions:
        parts.append(f"## Failed Sessions ({len(metrics.failure_sessions)} total)")
        for i, s in enumerate(metrics.failure_sessions[:max_sessions_in_prompt]):
            parts.append(_format_session_summary(s, i))
        if len(metrics.failure_sessions) > max_sessions_in_prompt:
            parts.append(f"... and {len(metrics.failure_sessions) - max_sessions_in_prompt} more")
        parts.append("")

    # Previous day report for comparison.
    if previous_report:
        parts.append("## Previous Day Report (for comparison)")
        # Truncate if very long.
        if len(previous_report) > 3000:
            parts.append(previous_report[:3000])
            parts.append("... [truncated]")
        else:
            parts.append(previous_report)
    else:
        parts.append("## Previous Day Report")
        parts.append("No previous day report available. Use 'N/A' for all delta/comparison values.")

    return "\n".join(parts)


def generate_daily_report(
    metrics: DailyMetrics,
    sessions: list[Session],
    date: str,
    previous_report: str | None = None,
) -> str:
    """Generate a daily markdown report using Gemini via Vertex AI.

    Args:
        metrics: Aggregated daily metrics.
        sessions: All sessions for the day.
        date: Target date in YYYY-MM-DD format.
        previous_report: Previous day's report markdown for delta comparisons.

    Returns:
        Generated markdown report content.

    Raises:
        Exception: On Vertex AI / Gemini API errors.
    """
    _ensure_init()

    model = GenerativeModel(
        GEMINI_MODEL,
        system_instruction=[_build_system_prompt()],
    )

    generation_config = GenerationConfig(
        temperature=GEMINI_TEMPERATURE,
        max_output_tokens=4096,
    )

    user_prompt = _build_user_prompt(metrics, sessions, date, previous_report)

    logger.info(
        "Generating daily report for %s (prompt length: %d chars)", date, len(user_prompt)
    )

    response = model.generate_content(
        user_prompt,
        generation_config=generation_config,
    )

    report_text = response.text
    logger.info("Report generated successfully (%d chars)", len(report_text))
    return report_text
