import { Storage } from '@google-cloud/storage';
import matter from 'gray-matter';
import type { FileNode, SearchResult } from './types';
import { semanticSearch } from './embeddings';

const BUCKET_NAME = process.env.GCS_BUCKET ?? 'hmca-agent-logs';
const USE_MOCK = process.env.USE_MOCK_DATA === 'true' || !process.env.GCS_BUCKET;

let storageInstance: Storage | null = null;

function getStorage(): Storage | null {
  if (USE_MOCK) return null;
  if (storageInstance) return storageInstance;
  try {
    storageInstance = new Storage();
    return storageInstance;
  } catch {
    console.warn('GCS not configured. Using mock data for local development.');
    return null;
  }
}

function getBucket() {
  const storage = getStorage();
  if (!storage) return null;
  return storage.bucket(BUCKET_NAME);
}

// ---------------------------------------------------------------------------
// Mock data for local dev when GCS is unavailable
// ---------------------------------------------------------------------------

const MOCK_TREE: FileNode[] = [
  {
    name: 'daily',
    path: 'daily/',
    type: 'folder',
    children: [
      {
        name: 'h-voice',
        path: 'daily/h-voice/',
        type: 'folder',
        children: [
          {
            name: '2026',
            path: 'daily/h-voice/2026/',
            type: 'folder',
            children: [
              {
                name: '03',
                path: 'daily/h-voice/2026/03/',
                type: 'folder',
                children: [
                  { name: '2026-03-25.md', path: 'daily/h-voice/2026/03/2026-03-25.md', type: 'file' },
                  { name: '2026-03-24.md', path: 'daily/h-voice/2026/03/2026-03-24.md', type: 'file' },
                  { name: '2026-03-23.md', path: 'daily/h-voice/2026/03/2026-03-23.md', type: 'file' },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: 'reports',
    path: 'reports/',
    type: 'folder',
    children: [
      {
        name: 'h-voice',
        path: 'reports/h-voice/',
        type: 'folder',
        children: [
          { name: '2026-03-25_weekly-bant-analysis.md', path: 'reports/h-voice/2026-03-25_weekly-bant-analysis.md', type: 'file' },
        ],
      },
    ],
  },
];

const MOCK_DAILY_LOG = `---
date: "2026-03-25"
agent: h-voice-call
type: daily-log
generated_at: "2026-03-25T09:00:00Z"
---

# H-Voice Daily Log — 2026-03-25

## Summary
> 총 47건 콜 수행, 연결률 72.3%, BANT 완료율 58.8%. 전일 대비 콜 수 +12%, 연결률 +3.2pp 상승. 딜러 연결 전환율은 소폭 하락.

## Key Metrics
| Metric | Value | vs Prev Day | Status |
|--------|-------|-------------|--------|
| Total Calls | 47 | +12% | 🟢 |
| Connection Rate | 72.3% | +3.2pp | 🟢 |
| BANT Completion Rate | 58.8% | -1.5pp | 🟡 |
| Avg Call Duration | 184s | +12s | 🟢 |
| Dealer Transfer Rate | 34.0% | -2.1pp | 🟡 |

## Session Breakdown
### Success Analysis
BANT 수집 완료 + 딜러 연결까지 성공한 16건 분석:
- **공통 패턴**: 고객이 첫 인사 후 30초 이내 긍정적 응답을 보인 경우 성공률이 높음
- **평균 소요 시간**: 210초 (3분 30초)
- **효과적 질문 순서**: Budget → Need → Authority → Timeline 순서가 가장 높은 완료율

### Failure Analysis
BANT 미완료 또는 조기 종료된 13건 분석:
- **주요 이탈 시점**: 2번째 질문(Need) 단계에서 47% 이탈
- **이탈 사유**: "지금 바쁘다" (38%), "관심 없다" (31%), 무응답/끊김 (31%)
- **패턴**: 오전 9-10시 콜의 조기 종료율이 오후 대비 2배 높음

## Anomalies & Alerts
- ⚠️ 오전 9-10시 시간대 연결률 52%로 전체 평균 대비 20pp 낮음
- ⚠️ 콜 ID #HV-0347에서 비정상적으로 긴 대기 시간 (45초) 발생
- ℹ️ 신규 Ofertas 폼 소스에서의 유입이 전일 대비 3배 증가

## Orchestrator Notes
오전 시간대의 낮은 연결률은 고객 업무 시작 시간과 겹치는 것으로 추정됩니다. 콜 스케줄링을 오전 10:30 이후로 조정하는 것을 권장합니다. BANT 2번째 질문에서의 높은 이탈률은 질문 방식의 개선이 필요할 수 있습니다.

---
*Generated by HMCA Agent Monitoring System*
`;

const MOCK_REPORT = `---
date: "2026-03-25"
agent: h-voice-call
type: report
period: "2026-03-19 ~ 2026-03-25"
requested_by: "system"
generated_at: "2026-03-25T10:00:00Z"
---

# Weekly BANT Analysis Report
> Period: 2026-03-19 ~ 2026-03-25

## Executive Summary
주간 BANT 수집 완료율 평균 57.2%로 전주 대비 +4.3pp 개선. Budget 질문의 응답률이 가장 높고 (78%), Authority 질문에서 가장 많은 이탈 발생 (완료율 61%).

## Trend Analysis
| 날짜 | BANT 완료율 | Budget | Authority | Need | Timeline |
|------|-----------|--------|-----------|------|----------|
| 03/19 | 52.1% | 74% | 58% | 65% | 71% |
| 03/20 | 54.3% | 76% | 60% | 67% | 69% |
| 03/21 | 55.8% | 75% | 59% | 68% | 72% |
| 03/22 | 58.2% | 79% | 62% | 70% | 73% |
| 03/23 | 57.4% | 77% | 61% | 69% | 71% |
| 03/24 | 60.3% | 81% | 64% | 72% | 74% |
| 03/25 | 58.8% | 80% | 63% | 71% | 73% |

## Key Findings
1. **Budget 질문 최고 응답률**: 구매 예산 관련 질문은 고객이 가장 편하게 응답 (78% avg)
2. **Authority 병목**: 의사결정권자 확인 질문에서 가장 많은 이탈. "누가 결정하시나요?" 표현이 부담을 줄 수 있음
3. **시간대별 차이**: 오후 2-4시 BANT 완료율이 오전 대비 15pp 높음
4. **소스별 차이**: Ofertas 폼 유입 고객의 BANT 완료율이 직접 유입 대비 22pp 높음

## Comparison
전주 (03/12 ~ 03/18) 대비:
- BANT 완료율: 52.9% → 57.2% (+4.3pp) 🟢
- 평균 콜 시간: 168s → 179s (+11s)
- 딜러 전환율: 31.2% → 33.8% (+2.6pp) 🟢

## Recommendations
1. **Authority 질문 리워딩**: "구매 과정에서 함께 상의하시는 분이 계신가요?"로 변경 검토
2. **콜 스케줄 최적화**: 오전 10:30 이전 콜 배치를 줄이고 오후 2-4시 슬롯 확대
3. **Ofertas 소스 확대**: 높은 전환율을 보이는 Ofertas 폼 유입 채널 강화

---
*Generated by HMCA Agent Monitoring System*
`;

const MOCK_FILES: Record<string, string> = {
  'daily/h-voice/2026/03/2026-03-25.md': MOCK_DAILY_LOG,
  'daily/h-voice/2026/03/2026-03-24.md': MOCK_DAILY_LOG.replace(/2026-03-25/g, '2026-03-24').replace('47건', '42건').replace('72.3%', '69.1%'),
  'daily/h-voice/2026/03/2026-03-23.md': MOCK_DAILY_LOG.replace(/2026-03-25/g, '2026-03-23').replace('47건', '39건').replace('72.3%', '68.5%'),
  'reports/h-voice/2026-03-25_weekly-bant-analysis.md': MOCK_REPORT,
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * List all files in the bucket as a hierarchical tree.
 */
export async function listFileTree(prefix?: string): Promise<FileNode[]> {
  const bucket = getBucket();
  if (!bucket) return MOCK_TREE;

  try {
    const [files] = await bucket.getFiles({ prefix: prefix ?? '' });
    const tree = buildTree(
      files
        .map((f) => f.name)
        .filter((name) => !name.endsWith('/')) // skip directory markers
    );
    return tree;
  } catch (error) {
    console.error('GCS listFileTree error:', error);
    return [];
  }
}

/**
 * Read a single markdown file from the bucket.
 */
export async function readFile(path: string): Promise<string | null> {
  const bucket = getBucket();
  if (!bucket) return MOCK_FILES[path] ?? null;

  try {
    const file = bucket.file(path);
    const [exists] = await file.exists();
    if (!exists) return null;

    const [buffer] = await file.download();
    return buffer.toString('utf-8');
  } catch (error) {
    console.error(`GCS readFile error for "${path}":`, error);
    return null;
  }
}

/**
 * Search across all markdown files.
 *
 * Supports two modes:
 * - `"semantic"` (default): uses Vertex AI embeddings + cosine similarity
 *   against the pre-built index at `index/embeddings.json`. Falls back to
 *   keyword search when the index is unavailable.
 * - `"keyword"`: traditional frontmatter + body text matching.
 *
 * Returns `{ results, mode }` where `mode` indicates which strategy was
 * actually used. The function signature stays backward-compatible.
 */
export async function searchFiles(
  query: string,
  prefix?: string,
  mode: 'semantic' | 'keyword' = 'semantic'
): Promise<SearchResult[]> {
  // Mock mode always uses keyword search
  const bucket = getBucket();
  if (!bucket) {
    return keywordSearch(query, prefix);
  }

  // Try semantic search when requested
  if (mode === 'semantic') {
    try {
      const results = await semanticSearch(query);
      if (results !== null) {
        return results;
      }
      // Index unavailable — fall through to keyword search
    } catch (error) {
      console.error('Semantic search failed, falling back to keyword:', error);
    }
  }

  return keywordSearchGCS(query, prefix, bucket);
}

/**
 * Indicates which search mode will actually be used (for UI display).
 */
export async function resolveSearchMode(
  requested: 'semantic' | 'keyword'
): Promise<'semantic' | 'keyword'> {
  if (requested === 'keyword') return 'keyword';

  const bucket = getBucket();
  if (!bucket) return 'keyword';

  try {
    const { isIndexAvailable } = await import('./embeddings');
    const available = await isIndexAvailable();
    return available ? 'semantic' : 'keyword';
  } catch {
    return 'keyword';
  }
}

/**
 * Keyword search against mock data.
 */
function keywordSearch(query: string, _prefix?: string): SearchResult[] {
  const q = query.toLowerCase();
  const results: SearchResult[] = [];
  for (const [filePath, content] of Object.entries(MOCK_FILES)) {
    const result = scoreFile(filePath, content, q);
    if (result) results.push(result);
  }
  results.sort((a, b) => b.score - a.score);
  return results;
}

/**
 * Keyword search against live GCS bucket.
 */
async function keywordSearchGCS(
  query: string,
  prefix: string | undefined,
  bucket: NonNullable<ReturnType<typeof getBucket>>
): Promise<SearchResult[]> {
  try {
    const [files] = await bucket.getFiles({
      prefix: prefix ?? '',
    });
    const mdFiles = files.filter((f) => f.name.endsWith('.md'));

    const queryLower = query.toLowerCase();
    const results: SearchResult[] = [];

    // Process files concurrently in batches to avoid overwhelming memory
    const BATCH_SIZE = 50;
    for (let i = 0; i < mdFiles.length; i += BATCH_SIZE) {
      const batch = mdFiles.slice(i, i + BATCH_SIZE);
      const batchResults = await Promise.allSettled(
        batch.map(async (file) => {
          const [buffer] = await file.download();
          const content = buffer.toString('utf-8');
          return scoreFile(file.name, content, queryLower);
        })
      );

      for (const result of batchResults) {
        if (result.status === 'fulfilled' && result.value) {
          results.push(result.value);
        }
      }
    }

    results.sort((a, b) => b.score - a.score);
    return results;
  } catch (error) {
    console.error('GCS keywordSearchGCS error:', error);
    return [];
  }
}

/**
 * Get the most recent daily log by lexicographic sorting of file names
 * under the daily-logs/ prefix.
 */
export async function getLatestDailyLog(): Promise<{
  path: string;
  content: string;
} | null> {
  const bucket = getBucket();

  if (!bucket) {
    return {
      path: 'daily/h-voice/2026/03/2026-03-25.md',
      content: MOCK_FILES['daily/h-voice/2026/03/2026-03-25.md'],
    };
  }

  try {
    const [files] = await bucket.getFiles({ prefix: 'daily-logs/' });
    const mdFiles = files
      .filter((f) => f.name.endsWith('.md'))
      .sort((a, b) => b.name.localeCompare(a.name));

    if (mdFiles.length === 0) return null;

    const latest = mdFiles[0];
    const [buffer] = await latest.download();
    return {
      path: latest.name,
      content: buffer.toString('utf-8'),
    };
  } catch (error) {
    console.error('GCS getLatestDailyLog error:', error);
    return null;
  }
}

/**
 * Upload a file to the bucket and return its GCS path.
 */
export async function writeFile(
  path: string,
  content: string
): Promise<string> {
  const bucket = getBucket();
  if (!bucket) {
    console.warn('GCS not configured. Skipping write for:', path);
    return path;
  }

  const file = bucket.file(path);
  await file.save(content, {
    contentType: 'text/markdown',
    metadata: { cacheControl: 'no-cache' },
  });
  return path;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Build a hierarchical FileNode tree from a flat list of GCS object paths.
 */
function buildTree(paths: string[]): FileNode[] {
  const root: Map<string, FileNode> = new Map();

  for (const filePath of paths) {
    const parts = filePath.split('/');
    let currentLevel = root;
    let currentPath = '';

    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      currentPath = currentPath ? `${currentPath}/${part}` : part;
      const isFile = i === parts.length - 1;

      if (!currentLevel.has(part)) {
        const node: FileNode = {
          name: part,
          path: isFile ? currentPath : `${currentPath}/`,
          type: isFile ? 'file' : 'folder',
          children: isFile ? undefined : [],
        };
        currentLevel.set(part, node);
      }

      const existing = currentLevel.get(part)!;
      if (!isFile) {
        // Navigate into children for the next level
        const childMap = new Map<string, FileNode>();
        if (existing.children) {
          for (const child of existing.children) {
            childMap.set(child.name, child);
          }
        }
        currentLevel = childMap;
        // Sync childMap back to existing.children after processing
        // We need a reference-based approach instead
      }
    }
  }

  // Re-implement with a simpler recursive insert
  return buildTreeSimple(paths);
}

function buildTreeSimple(paths: string[]): FileNode[] {
  interface TreeMap {
    [key: string]: TreeMap | null; // null = leaf (file)
  }

  const treeMap: TreeMap = {};

  for (const filePath of paths) {
    const parts = filePath.split('/');
    let current: TreeMap = treeMap;
    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      const isLast = i === parts.length - 1;
      if (isLast) {
        current[part] = null;
      } else {
        if (current[part] === null || current[part] === undefined) {
          current[part] = {};
        }
        current = current[part] as TreeMap;
      }
    }
  }

  function mapToNodes(map: TreeMap, parentPath: string): FileNode[] {
    const nodes: FileNode[] = [];
    const entries = Object.entries(map).sort(([a], [b]) => a.localeCompare(b));

    for (const [name, value] of entries) {
      const fullPath = parentPath ? `${parentPath}/${name}` : name;
      if (value === null) {
        nodes.push({ name, path: fullPath, type: 'file' });
      } else {
        nodes.push({
          name,
          path: `${fullPath}/`,
          type: 'folder',
          children: mapToNodes(value, fullPath),
        });
      }
    }
    return nodes;
  }

  return mapToNodes(treeMap, '');
}

/**
 * Score a file against a search query. Returns null if no match.
 */
function scoreFile(
  filePath: string,
  content: string,
  queryLower: string
): SearchResult | null {
  let score = 0;
  let frontmatterRecord: Record<string, string> = {};
  let body = content;
  let title = '';

  try {
    const parsed = matter(content);
    body = parsed.content;
    frontmatterRecord = Object.fromEntries(
      Object.entries(parsed.data).map(([k, v]) => [k, String(v)])
    );

    // Check frontmatter fields for matches
    for (const value of Object.values(frontmatterRecord)) {
      if (String(value).toLowerCase().includes(queryLower)) {
        score += 10;
      }
    }
  } catch {
    // If frontmatter parsing fails, search raw content
  }

  // Extract first H1 as title
  const titleMatch = body.match(/^#\s+(.+)$/m);
  if (titleMatch) {
    title = titleMatch[1].trim();
    if (title.toLowerCase().includes(queryLower)) {
      score += 5;
    }
  }

  // Body text match
  if (body.toLowerCase().includes(queryLower)) {
    score += 1;
  }

  if (score === 0) return null;

  // Extract snippet around the first match in body
  const snippet = extractSnippet(body, queryLower);

  return {
    path: filePath,
    title: title || filePath.split('/').pop()?.replace('.md', '') || filePath,
    snippet,
    frontmatter: frontmatterRecord,
    score,
  };
}

/**
 * Extract a short snippet of text around the first occurrence of the query.
 */
function extractSnippet(text: string, queryLower: string): string {
  const SNIPPET_RADIUS = 80;
  const plainText = text.replace(/[#*_`~\[\]()>]/g, '').trim();
  const idx = plainText.toLowerCase().indexOf(queryLower);

  if (idx === -1) {
    return plainText.slice(0, SNIPPET_RADIUS * 2) + (plainText.length > SNIPPET_RADIUS * 2 ? '...' : '');
  }

  const start = Math.max(0, idx - SNIPPET_RADIUS);
  const end = Math.min(plainText.length, idx + queryLower.length + SNIPPET_RADIUS);
  const prefix = start > 0 ? '...' : '';
  const suffix = end < plainText.length ? '...' : '';

  return `${prefix}${plainText.slice(start, end)}${suffix}`;
}
