import { Storage } from '@google-cloud/storage';
import matter from 'gray-matter';
import type { FileNode, SearchResult } from './types';
import { semanticSearch } from './embeddings';

const BUCKET_NAME = process.env.GCS_BUCKET ?? 'h-agent-log';
const USE_MOCK = process.env.USE_MOCK_DATA === 'true' || !process.env.GCS_BUCKET;

let storageInstance: Storage | null = null;

function getStorage(): Storage | null {
  if (USE_MOCK) return null;
  if (storageInstance) return storageInstance;
  try {
    storageInstance = new Storage();
    return storageInstance;
  } catch {
    console.warn('GCS not configured. Using mock data for local development.');
    return null;
  }
}

function getBucket() {
  const storage = getStorage();
  if (!storage) return null;
  return storage.bucket(BUCKET_NAME);
}

// ---------------------------------------------------------------------------
// Mock data for local dev when GCS is unavailable
// ---------------------------------------------------------------------------

const MOCK_TREE: FileNode[] = [
  {
    name: 'daily',
    path: 'daily/',
    type: 'folder',
    children: [
      {
        name: 'h-voice',
        path: 'daily/h-voice/hmb/',
        type: 'folder',
        children: [
          { name: '2026-03-29.md', path: 'daily/h-voice/hmb/2026-03-29.md', type: 'file' },
          { name: '2026-03-28.md', path: 'daily/h-voice/hmb/2026-03-28.md', type: 'file' },
          { name: '2026-03-27.md', path: 'daily/h-voice/hmb/2026-03-27.md', type: 'file' },
        ],
      },
    ],
  },
  {
    name: 'reports',
    path: 'reports/',
    type: 'folder',
    children: [
      {
        name: 'h-voice',
        path: 'reports/h-voice/',
        type: 'folder',
        children: [
          { name: '2026-03-23_2026-03-29.md', path: 'reports/h-voice/2026-03-23_2026-03-29.md', type: 'file' },
        ],
      },
    ],
  },
];

const MOCK_DAILY_LOG = `---
date: "2026-03-29"
agent: h-voice-call
type: daily-log
generated_at: "2026-03-29T09:00:00Z"
---

# H-Voice Daily Log — 2026-03-29

## Executive Summary
> 총 52건 콜 수행, Connected Rate 78.8%, Acceptance Rate 65.9%. 전일 대비 콜 수 +8%, Acceptance Rate +2.1pp 상승.
> Qualification Rate 54.2%로 안정세 유지. 시승 예약 6건으로 전일(4건) 대비 증가.
> Novo Creta 관심 비중 64%로 HB20(28%) 대비 2배 이상. Payment Method 수집률 36%로 최저.

---

## 1. Call Funnel Metrics

| Stage | Count | Rate | vs Prev Day | Status |
|-------|-------|------|-------------|--------|
| Total Calls | 52 | — | +8% | |
| Voicemail | 7 | 13.5% | -1.2pp | 🟢 |
| Hung Up (조기 종료) | 4 | 7.7% | +0.5pp | 🟡 |
| Connected (연결) | 41 | 78.8% | +0.7pp | 🟢 |
| Accepted (수락) | 27 | 65.9% of connected | +2.1pp | 🟢 |
| Qualified (퀄리파이) | 14 | 54.2% of accepted | +1.8pp | 🟢 |
| Dealer Consent (딜러 동의) | 11 | 40.7% of accepted | -0.5pp | 🟡 |
| Test Drive Scheduled (시승 예약) | 6 | 22.2% of accepted | +3.7pp | 🟢 |

## 2. Qualification Depth (퀄리피케이션 수집 현황)

| 항목 | 수집 건수 | 수집률 (Accepted 기준) |
|------|----------|---------------------|
| Model of Interest (관심 차종) | 27 | 100.0% |
| Trim / Version (트림) | 8 | 29.6% |
| Purchase Timeframe (구매 시기) | 18 | 66.7% |
| Payment Method (결제 방식) | 10 | 36.0% |
| Trade-in (보상 판매) | 15 | 55.6% |
| Test Drive Interest (시승 관심) | 16 | 59.3% |
| Test Drive Slot (시승 일정) | 6 | 22.2% |
| Preferred Contact Channel (선호 연락 채널) | 14 | 51.9% |

## 3. Call Performance (콜 성과)

| 지표 | 값 | vs Prev Day |
|------|---|-------------|
| 평균 통화 시간 (전체) | 68초 | +5초 |
| 평균 통화 시간 (Accepted만) | 142초 | +8초 |
| 평균 통화 시간 (Voicemail) | 15초 | — |
| 고객 종료 비율 (Ended by Customer) | 71.2% | -1.3pp |
| AI 종료 비율 (Ended by AI) | 28.8% | +1.3pp |

## 4. Model & Dealer Insights (차종 및 딜러 분석)

### 차종별 현황
| 차종 | 콜 수 | Acceptance Rate | Qualification Rate |
|------|-------|----------------|-------------------|
| Hyundai Novo Creta | 33 | 69.7% | 60.9% |
| Hyundai Novo HB20 | 15 | 60.0% | 44.4% |
| Hyundai Tucson | 4 | 50.0% | 50.0% |

### 딜러별 현황 (Consent Rate 상위)
| 딜러명 | 콜 수 | Consent Rate | 시승 예약 |
|--------|-------|-------------|----------|
| Via VR - Volta Redonda | 4 | 75.0% | 2 |
| Grande Coreia - Fortaleza | 5 | 60.0% | 1 |
| Saga - Anápolis | 3 | 66.7% | 1 |
| Nobre - Mogi das Cruzes | 3 | 33.3% | 1 |
| Pateo - Salvador | 4 | 25.0% | 0 |

### 채널별 현황
| 채널 | 콜 수 | Acceptance Rate |
|------|-------|----------------|
| meta | 31 | 71.0% |
| web | 21 | 57.1% |

## 5. Anomalies & Alerts (이상 징후)
- ⚠️ Payment Method 수집률 36.0% — 전체 필드 중 최저, 스크립트 내 질문 시점 검토 필요
- ℹ️ Meta 채널 Acceptance Rate가 Web 대비 13.9pp 높음 — 채널 투자 비중 검토 가능

## 6. Orchestrator Notes (분석 소견)
- Novo Creta의 Qualification Rate(60.9%)가 HB20(44.4%)보다 16.5pp 높습니다. HB20 스크립트에 Creta의 효과적인 질문 순서를 반영하는 것을 검토하세요.
- Payment Method 단계에서의 이탈이 지속되고 있습니다. "결제 방식을 정하셨나요?" 대신 "어떤 방식이 가장 편하실까요?"로 리워딩을 제안합니다.
- Meta 채널의 높은 성과(Acceptance Rate 71%)를 기반으로 Meta 광고 예산 증액을 검토할 수 있습니다.
- 시승 예약 6건은 이번 주 최고치입니다. 시승 전환이 높은 Via VR - Volta Redonda 딜러의 패턴을 분석하세요.

---
*Generated by H-Orchestrator Agent Monitoring System*
`;

const MOCK_REPORT = `---
date: "2026-03-29"
agent: h-voice-call
type: report
period: "2026-03-23 ~ 2026-03-29"
requested_by: "system"
generated_at: "2026-03-29T10:00:00Z"
---

# H-Voice 분석 리포트 — 2026-03-23 ~ 2026-03-29

## Executive Summary
> 분석 기간 총 312건 콜 수행, Acceptance Rate 64.8%로 전 기간 대비 +3.2pp 개선.
> Qualification Rate 51.4%로 안정세. 시승 예약 28건으로 전 기간 대비 +40%.
> Novo Creta가 전체 콜의 63%를 차지하며 HB20 대비 Qualification Rate 18pp 높음.
> 핵심 개선 포인트: Payment Method 수집률 38%로 가장 낮아 스크립트 조정 필요.

---

## 1. 기간 요약 (Period Overview)

| 지표 | 현재 기간 | 이전 동일 기간 | 변화 | 추세 |
|------|----------|--------------|------|------|
| 총 콜 수 | 312 | 285 | +9.5% | 🟢 |
| Voicemail Rate | 14.1% | 16.8% | -2.7pp | 🟢 |
| Connected Rate | 77.9% | 74.4% | +3.5pp | 🟢 |
| Acceptance Rate | 64.8% | 61.6% | +3.2pp | 🟢 |
| Qualification Rate | 51.4% | 49.1% | +2.3pp | 🟢 |
| Dealer Consent Rate | 39.2% | 37.8% | +1.4pp | 🟡 |
| Test Drive 예약 건수 | 28 | 20 | +40% | 🟢 |
| 평균 통화 시간 (Accepted) | 138초 | 131초 | +7초 | 🟡 |

## 2. 일별 추이 (Daily Trend)

| 날짜 | 총 콜 | Connected | Accepted | Qualified | Consent | Test Drive |
|------|-------|-----------|----------|-----------|---------|-----------|
| 03/23 | 39 | 30 | 19 | 9 | 7 | 3 |
| 03/24 | 42 | 33 | 21 | 11 | 8 | 4 |
| 03/25 | 47 | 38 | 25 | 13 | 10 | 4 |
| 03/26 | 44 | 34 | 22 | 11 | 9 | 3 |
| 03/27 | 45 | 35 | 24 | 12 | 9 | 4 |
| 03/28 | 43 | 33 | 22 | 12 | 8 | 4 |
| 03/29 | 52 | 41 | 27 | 14 | 11 | 6 |

## 3. 퍼널 분석 (Funnel Analysis)

### 단계별 이탈률
| 단계 전환 | 전환율 | 이탈 건수 | 주요 이탈 사유 |
|-----------|-------|----------|--------------|
| 콜 시도 → Connected | 77.9% | 69 | Voicemail(44건), 조기 종료(25건) |
| Connected → Accepted | 64.8% | 86 | 콜 거부("관심 없음", "바쁨") |
| Accepted → Qualified | 51.4% | 77 | Payment Method 단계 이탈 집중 |
| Qualified → Dealer Consent | 76.3% | 19 | 딜러 연결 거부 |
| Dealer Consent → Test Drive | 45.9% | 34 | 일정 미확정 |

## 4. 세그먼트 분석 (Segment Analysis)

### 차종별 성과
| 차종 | 콜 수 | 비중 | Acceptance Rate | Qualification Rate | Consent Rate | 시승 예약 |
|------|-------|------|----------------|-------------------|-------------|----------|
| Hyundai Novo Creta | 197 | 63% | 68.4% | 55.2% | 42.1% | 19 |
| Hyundai Novo HB20 | 94 | 30% | 57.4% | 44.4% | 33.3% | 7 |
| Hyundai Tucson | 21 | 7% | 61.9% | 46.2% | 38.5% | 2 |

## 5. 주요 발견 (Key Findings)
1. **Novo Creta 우위 지속**: Creta의 Qualification Rate(55.2%)가 HB20(44.4%) 대비 10.8pp 높음
2. **Payment Method 병목**: 전체 필드 중 수집률 38%로 최저 — 질문 시점 이탈 집중
3. **Meta 채널 효과**: Meta 유입 리드의 Acceptance Rate가 Web 대비 12pp 높음
4. **시승 예약 급증**: 전 기간(20건) 대비 +40% — Via VR, Grande Coreia 딜러 기여
5. **오전 시간대 Voicemail 집중**: 09-10시 Voicemail Rate 32%로 전체 평균(14.1%) 대비 2배

## 6. 개선 권장사항 (Recommendations)
1. **Payment Method 질문 리워딩**: "결제 방식을 정하셨나요?" → "어떤 방식이 가장 편하실까요?" 변경 검토
2. **콜 스케줄 최적화**: 오전 10시 이전 콜 비중 축소, 오후 2-4시 슬롯 확대
3. **HB20 스크립트 개선**: Creta에서 효과적인 퀄리피케이션 순서를 HB20에 반영
4. **Meta 채널 투자 확대**: 높은 전환율 기반 Meta 광고 예산 증액 검토
5. **시승 연결 프로세스 강화**: Consent 후 시승 전환율(45.9%) 개선을 위한 즉시 일정 제안 스크립트 추가

---
*Generated by H-Orchestrator Agent Monitoring System*
`;

const MOCK_FILES: Record<string, string> = {
  'daily/h-voice/hmb/2026-03-29.md': MOCK_DAILY_LOG,
  'daily/h-voice/hmb/2026-03-28.md': MOCK_DAILY_LOG.replace(/2026-03-29/g, '2026-03-28').replace('52건', '43건').replace('78.8%', '78.1%'),
  'daily/h-voice/hmb/2026-03-27.md': MOCK_DAILY_LOG.replace(/2026-03-29/g, '2026-03-27').replace('52건', '45건').replace('78.8%', '77.8%'),
  'reports/h-voice/2026-03-23_2026-03-29.md': MOCK_REPORT,
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * List all files in the bucket as a hierarchical tree.
 */
export async function listFileTree(prefix?: string): Promise<FileNode[]> {
  const bucket = getBucket();
  if (!bucket) return MOCK_TREE;

  try {
    const HIDDEN_PREFIXES = ['index/', 'templates/'];
    const [files] = await bucket.getFiles({ prefix: prefix ?? '' });
    const tree = buildTreeSimple(
      files
        .map((f) => f.name)
        .filter((name) => !name.endsWith('/'))
        .filter((name) => !HIDDEN_PREFIXES.some((p) => name.startsWith(p)))
    );
    return tree;
  } catch (error) {
    console.error('GCS listFileTree error:', error);
    return [];
  }
}

/**
 * Strip markdown code fences that Gemini sometimes wraps around output,
 * and ensure frontmatter has opening `---`.
 */
function cleanMarkdown(raw: string): string {
  let content = raw.trim();

  // Remove wrapping code fences: ```markdown ... ``` or ``` ... ```
  const fenceMatch = content.match(/^```(?:markdown)?\s*\n([\s\S]*?)```\s*$/);
  if (fenceMatch) {
    content = fenceMatch[1].trim();
  }

  // Fix markdown tables and headings line by line
  const lines = content.split('\n');
  const fixed: string[] = [];
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Fix table separator row: match column count to header row
    if (/^\|[\s-:]+\|/.test(line) && i > 0 && lines[i - 1].startsWith('|')) {
      const headerCols = lines[i - 1].split('|').filter(c => c.trim() !== '').length;
      const sepCols = line.split('|').filter(c => c.trim() !== '').length;
      if (sepCols !== headerCols) {
        const sep = '|' + Array(headerCols).fill('---|').join('') ;
        fixed.push(sep);
      } else {
        fixed.push(line);
      }
    } else {
      fixed.push(line);
    }

    // Insert blank line after headings if next line is not blank
    if (/^#{1,6}\s+/.test(line) && i + 1 < lines.length && lines[i + 1].trim() !== '') {
      fixed.push('');
    }
  }
  content = fixed.join('\n');

  // Ensure frontmatter starts with ---
  if (/^[a-z_]+\s*:/.test(content) && !content.startsWith('---')) {
    content = '---\n' + content;
    // Ensure closing --- exists after frontmatter block
    const lines = content.split('\n');
    let closingIdx = -1;
    for (let i = 1; i < lines.length; i++) {
      if (lines[i].trim() === '---') { closingIdx = i; break; }
      if (lines[i].startsWith('#') || lines[i].trim() === '') {
        // Insert --- before the first blank line or heading after frontmatter
        lines.splice(i, 0, '---');
        closingIdx = i;
        break;
      }
    }
    if (closingIdx === -1) {
      // No closing found, try to find where frontmatter ends
      for (let i = 1; i < lines.length; i++) {
        if (!/^[a-z_]+\s*:/.test(lines[i]) && lines[i].trim() !== '') {
          lines.splice(i, 0, '---');
          break;
        }
      }
    }
    content = lines.join('\n');
  }

  return content;
}

/**
 * Read a single markdown file from the bucket.
 */
export async function readFile(path: string): Promise<string | null> {
  const bucket = getBucket();
  if (!bucket) return MOCK_FILES[path] ?? null;

  try {
    const file = bucket.file(path);
    const [exists] = await file.exists();
    if (!exists) return null;

    const [buffer] = await file.download();
    return cleanMarkdown(buffer.toString('utf-8'));
  } catch (error) {
    console.error(`GCS readFile error for "${path}":`, error);
    return null;
  }
}

/**
 * Search across all markdown files.
 */
export async function searchFiles(
  query: string,
  prefix?: string,
  mode: 'semantic' | 'keyword' = 'semantic'
): Promise<SearchResult[]> {
  const bucket = getBucket();
  if (!bucket) {
    return keywordSearch(query, prefix);
  }

  if (mode === 'semantic') {
    try {
      const results = await semanticSearch(query);
      if (results !== null) {
        return results;
      }
    } catch (error) {
      console.error('Semantic search failed, falling back to keyword:', error);
    }
  }

  return keywordSearchGCS(query, prefix, bucket);
}

/**
 * Indicates which search mode will actually be used.
 */
export async function resolveSearchMode(
  requested: 'semantic' | 'keyword'
): Promise<'semantic' | 'keyword'> {
  if (requested === 'keyword') return 'keyword';

  const bucket = getBucket();
  if (!bucket) return 'keyword';

  try {
    const { isIndexAvailable } = await import('./embeddings');
    const available = await isIndexAvailable();
    return available ? 'semantic' : 'keyword';
  } catch {
    return 'keyword';
  }
}

/**
 * Get the most recent daily log.
 */
export async function getLatestDailyLog(): Promise<{
  path: string;
  content: string;
} | null> {
  const bucket = getBucket();

  if (!bucket) {
    return {
      path: 'daily/h-voice/hmb/2026-03-29.md',
      content: MOCK_FILES['daily/h-voice/hmb/2026-03-29.md'],
    };
  }

  try {
    const [files] = await bucket.getFiles({ prefix: 'daily/h-voice/hmb/' });
    const mdFiles = files
      .filter((f) => f.name.endsWith('.md'))
      .sort((a, b) => b.name.localeCompare(a.name));

    if (mdFiles.length === 0) return null;

    const latest = mdFiles[0];
    const [buffer] = await latest.download();
    return {
      path: latest.name,
      content: buffer.toString('utf-8'),
    };
  } catch (error) {
    console.error('GCS getLatestDailyLog error:', error);
    return null;
  }
}

/**
 * Upload a file to the bucket.
 */
export async function writeFile(
  path: string,
  content: string
): Promise<string> {
  const bucket = getBucket();
  if (!bucket) {
    console.warn('GCS not configured. Storing in mock data for:', path);
    MOCK_FILES[path] = content;
    return path;
  }

  const file = bucket.file(path);
  await file.save(content, {
    contentType: 'text/markdown',
    metadata: { cacheControl: 'no-cache' },
  });
  return path;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function keywordSearch(query: string, _prefix?: string): SearchResult[] {
  const q = query.toLowerCase();
  const results: SearchResult[] = [];
  for (const [filePath, content] of Object.entries(MOCK_FILES)) {
    const result = scoreFile(filePath, content, q);
    if (result) results.push(result);
  }
  results.sort((a, b) => b.score - a.score);
  return results;
}

async function keywordSearchGCS(
  query: string,
  prefix: string | undefined,
  bucket: NonNullable<ReturnType<typeof getBucket>>
): Promise<SearchResult[]> {
  try {
    const [files] = await bucket.getFiles({
      prefix: prefix ?? '',
    });
    const mdFiles = files.filter((f) => f.name.endsWith('.md'));

    const queryLower = query.toLowerCase();
    const results: SearchResult[] = [];

    const BATCH_SIZE = 50;
    for (let i = 0; i < mdFiles.length; i += BATCH_SIZE) {
      const batch = mdFiles.slice(i, i + BATCH_SIZE);
      const batchResults = await Promise.allSettled(
        batch.map(async (file) => {
          const [buffer] = await file.download();
          const content = buffer.toString('utf-8');
          return scoreFile(file.name, content, queryLower);
        })
      );

      for (const result of batchResults) {
        if (result.status === 'fulfilled' && result.value) {
          results.push(result.value);
        }
      }
    }

    results.sort((a, b) => b.score - a.score);
    return results;
  } catch (error) {
    console.error('GCS keywordSearchGCS error:', error);
    return [];
  }
}

function buildTreeSimple(paths: string[]): FileNode[] {
  interface TreeMap {
    [key: string]: TreeMap | null;
  }

  const treeMap: TreeMap = {};

  for (const filePath of paths) {
    const parts = filePath.split('/');
    let current: TreeMap = treeMap;
    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      const isLast = i === parts.length - 1;
      if (isLast) {
        current[part] = null;
      } else {
        if (current[part] === null || current[part] === undefined) {
          current[part] = {};
        }
        current = current[part] as TreeMap;
      }
    }
  }

  function mapToNodes(map: TreeMap, parentPath: string): FileNode[] {
    const nodes: FileNode[] = [];
    const entries = Object.entries(map).sort(([a], [b]) => a.localeCompare(b));

    for (const [name, value] of entries) {
      const fullPath = parentPath ? `${parentPath}/${name}` : name;
      if (value === null) {
        nodes.push({ name, path: fullPath, type: 'file' });
      } else {
        nodes.push({
          name,
          path: `${fullPath}/`,
          type: 'folder',
          children: mapToNodes(value, fullPath),
        });
      }
    }
    return nodes;
  }

  return mapToNodes(treeMap, '');
}

function scoreFile(
  filePath: string,
  content: string,
  queryLower: string
): SearchResult | null {
  let score = 0;
  let frontmatterRecord: Record<string, string> = {};
  let body = content;
  let title = '';

  try {
    const parsed = matter(content);
    body = parsed.content;
    frontmatterRecord = Object.fromEntries(
      Object.entries(parsed.data).map(([k, v]) => [k, String(v)])
    );

    for (const value of Object.values(frontmatterRecord)) {
      if (String(value).toLowerCase().includes(queryLower)) {
        score += 10;
      }
    }
  } catch {
    // If frontmatter parsing fails, search raw content
  }

  const titleMatch = body.match(/^#\s+(.+)$/m);
  if (titleMatch) {
    title = titleMatch[1].trim();
    if (title.toLowerCase().includes(queryLower)) {
      score += 5;
    }
  }

  if (body.toLowerCase().includes(queryLower)) {
    score += 1;
  }

  if (score === 0) return null;

  const snippet = extractSnippet(body, queryLower);

  return {
    path: filePath,
    title: title || filePath.split('/').pop()?.replace('.md', '') || filePath,
    snippet,
    frontmatter: frontmatterRecord,
    score,
  };
}

function extractSnippet(text: string, queryLower: string): string {
  const SNIPPET_RADIUS = 80;
  const plainText = text.replace(/[#*_`~\[\]()>]/g, '').trim();
  const idx = plainText.toLowerCase().indexOf(queryLower);

  if (idx === -1) {
    return plainText.slice(0, SNIPPET_RADIUS * 2) + (plainText.length > SNIPPET_RADIUS * 2 ? '...' : '');
  }

  const start = Math.max(0, idx - SNIPPET_RADIUS);
  const end = Math.min(plainText.length, idx + queryLower.length + SNIPPET_RADIUS);
  const prefix = start > 0 ? '...' : '';
  const suffix = end < plainText.length ? '...' : '';

  return `${prefix}${plainText.slice(start, end)}${suffix}`;
}
